### ISSUE TITLE
Logging class deletes existing logging configuration

### ISSUE THREAD

**Issue by jklynch** [cokelaer/easydev#15]
I just found Bioservices a few weeks ago and I think it is a great project. Thanks for all your work.

I started using bioservices.eutils in a project and noticed that as soon as I instantiate EUtils I no longer get any debug messages from any loggers in my project. It looks like the Logging class from easydev is deleting the logging configuration my script established.

I think lines 72 and 73 in logging_tools.py are the problem. It would be helpful if this behavior were optional.

**Comment by cokelaer** [comment]
Fixed this issue in version 0.9.36 of easydev. I will update bioservices accordingly in the next days.
