### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by tapdiego-amzn** [cokelaer/easydev#21]
Project license is identified as BSD-3-Clause in both https://github.com/cokelaer/easydev/blob/master/COPYING and  https://github.com/cokelaer/easydev/blob/master/setup.py, but the license headers in most source code files still explicitly mention GPL-3.0, e.g. https://github.com/cokelaer/easydev/blob/master/easydev/__init__.py#L10. Can you please clarify whether those GPL-3.0 licensing statements are still valid, or whether they should be fixed to reflect the actual license?

**Comment by cokelaer** [comment]
Fixed in v0.12.2
