### ISSUE TITLE
Consider migrating away from appdirs (upstream dead)

### ISSUE THREAD

**Issue by hosiet** [cokelaer/easydev#23]
According to https://github.com/ActiveState/appdirs/blob/master/README.rst , the appdirs project is now dead upstream. Even though easydev will not be immediately affected due to embedding appdirs source code, it might not be a good idea to use this dead project in the long term. The appdirs upstream recommends migrating to using `platformdirs` ( https://pypi.org/project/platformdirs/ ) instead.

**Comment by cokelaer** [comment]
Fixed in v0.12.2
